### ISSUE TITLE
Upgrade bugs and improvements remaining

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#295]
Time I start working on these in the open:
- [x] Make sure that email alerts identify what court the item is from.
- [x] Brian's duration bug (#294)
- [x] Bulk files require postgres password for django user.
- [x] sitemap.xml is crashing Firefox and Chrome
- [x] Juriscraper isn't working for several OA jurisductions, 
- [x] Juriscraper lacks good reporting for OA like on opinions
- [x] Juriscraper os failing for Texas opinions. 
- [x] Maryland OA needs to be added to the court picker.
- [x] We have > 10k OA files in a spreadsheet to import
- [x] Commits for Solr indexes need to be set to every five minutes and citation_finding needs to be spread over the hour after a scraper runs. Items should return in results after the first commit, but citations will appear later. avconv should be spread over the hour after OA scrapers run.
- [x] Bulk data can be moved to an incremental system. (#293)
- [x] Audio doesn't play on Android (#292)
- [x] The reporting email might be failing
- [x] Backups are still mostly off.
- [x] Oral Arg Podcasts should be submitted to iTunes, Stitcher and Overcast (?)
- [x] Create symlinks for wma and mp4 when the scraper is calm.
- [x] Avconv appears to be eating 100% CPU when doing mp4 files and taking an extended time to complete. There's a chance that we need to install from source to get a fix: https://lists.libav.org/pipermail/libav-bugs/2012-November/001860.html
- [x] Alert emails don't distinguish between OA and O (#297)
- [x] Attempt re-run of bulk data creation.
- [x] Sort out weird SELECT statement and turn off `track_activities` (then service posgresql reload)
