### ISSUE TITLE
OA's from data donation have scrambled meta data

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#311]
Somehow the CSV that we ended up using got scrambled so the audio downloaded doesn't line up with the meta data in the database. This is pretty bad and reminds me of my dislike of Spreadsheets (also how rusty I am with them).

I'll be fixing this over the next hour or two:
- [x] All basic meta data needs to be fixed in the DB and updated in Solr (duration, case name, court, etc.)
- [x] Files need to be moved to the correct locations on disk (they're in date-based directories and the dates are about to change) and renamed (the files have the case-name for their file name).
- [x] id3 data needs to be updated (includes new album art, album name, comments, etc.)
- [x] Associated dockets need to be fixed (they have jurisdiction info, case name, etc.)

Most of this will be pretty easy. Just have to be very careful not to make any mistakes. As this runs, we'll surely have duplicates, but I can mitigate the front end weirdness by doing a single commit at the end.
