### ISSUE TITLE
Hit list for pushing new version live

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#361]
This will be an ongoing ticket so people can see what's left before the big upgrade. Still lots to do, but it's getting close.

Pre-launch:

 - [x] Answer infrastructure questions:
    - What server will host the new installation? A: The new one.
    - Is now the time to move celery to its own server and to move it to reddis? A: Yep.
    - Do we have enough disk space? A: On the new server, sure.
    - How does virtualenv work with apache?
 - [x] Make the migration script resumable and address all the TODOs it has in its comments.
 - [x] Finish updating scrapers
 - [x] Finish updating search
 - [x] Work through any other TODO comments that are identified by Intellij
 - [x] Tweak Apache, Solr, Postgres settings for max performance and to mirror old CL.
 - [x] Finish API
 - [x] Mail server junk:
    - [x] Server name
    - [x] Any nasty signatures or whatever?
 - [x] Issue #416 is a blocker, alas.

Launch:

 - [x] Get latest code into `/var/www/cl/`
 - [x] Complete the applicable parts of the CL installation:
     - [x] Create virtualenv and fill it with requirements.txt
     - [x] Create a new database called cl
     - [x] ...?
 - [x] Disable any cron job that'll modify data
 - [x] Put the regular site in maintenance mode so the data is stable
 - [x] Run manage.py mega_migrate
 - [x] Update proxy config to point to old server in smarter way (it currently uses courtlistener.com, which will summarily break when the new server goes live).
 - [x] Run the citation finder!
 - [x] Issue #380 (to fix slug links -- easier to fix this after the migration has run)

Post launch:

 - [x] Enable the cron jobs for scrapers and other processes
 - [x] Regenerate citegeist scores, and note speed

**Comment by mlissner** [comment]
2FA is in place using the [same tutorial I always use][1]. 

I was also able to move the old tokens over by simply copying each user's `.google_authenticator` file from their home directory.

[1]: http://www.howtogeek.com/121650/how-to-secure-ssh-with-google-authenticators-two-factor-authentication/

**Comment by mlissner** [comment]
I've enabled automatic updates for security packages using [a tutorial on the Ubuntu wiki][1].

I tweaked some of the settings. In particular, it's set up to do automatic security upgrades, sending any errors to my FLP email address. It is *not* empowered to reboot itself, but it should email me if it needs a reboot. To allow it to email me I had to install `bsd-mailx`, which promises to be a "simple mail user agent".

[1]: https://help.ubuntu.com/community/AutomaticSecurityUpdates

**Comment by mlissner** [comment]
Mail server is done. Notes are in issue #415.

**Comment by mlissner** [comment]
This guy is finally done. It was kind of waiting for citegeist and the citation algos to get really good. Those are done now, so we're on our way. 

I kept a second list on my laptop while working on this, which I'll paste in here just in case it's useful next time we do a big upgrade like this:

 - [x] Turn everything off:
    - [x] Put CL1 and CL2 in maintenance mode
    - [x] Disable all cron jobs on all servers
    - [x] Knock the crawlers offline.
 - [x] Migrate the database data.
    - [x] Update sequences using: https://wiki.postgresql.org/wiki/Fixing_Sequences
 - [x] Move the sata disk to the new system (@brian will be physically doing this).
    - [x] Fix symlinks to /sata
 - [x] Update the network to make new server live Update apache to move it to port 443.
 - [x] Fix issue #380 having to do with empty slugs
 - [x] Update a proxy config to make old APIs work properly
 - [x] Turn everything back on:
    - [x] Re-enable all cronjobs
    - [x] Turn off maintance mode
    - [x] Turn off DEBUG mode
 - [x] ANNOUNCE
 - [x] Update all solr cores
    - [x] Update collection1 with recent
    - [x] Update complete collection1
    - [x] Update complete audio
 

BUGS DISCOVERED:
 - [x] Juriscraper is on at reboot.
 - [x] www not redirecting properly.
